kind: pipeline
type: ssh
name: Laradock(porxy_pass)_(DB_REDIS)->easyswoole(HTTPS/WSS:N集群) 

servers:
  host : 
    from_secret: host
  user : 
    from_secret : username
  ssh_key : 
    from_secret : ssh_key

platform:
  os : linux
  arch : amd64

clone :
  depth : 10

steps:

- name: install
  image: composer
  commands:
  - composer install
  - composer dump-autoload


trigger:
  branch:
    - master